export const LOGIN = 'LOGIN';
export const LOGIN_WITH_CALLBACK = 'LOGIN_WITH_CALLBACK';

export const GET_NEWS = 'GET_NEWS';

export const CHANGE_QUEUE_STATUS = 'CHANGE_QUEUE_STATUS';
export const ADD_FRIEND_TO_QUEUE = 'ADD_FRIEND_TO_QUEUE';
export const REMOVE_FRIEND_FROM_QUEUE = 'REMOVE_FRIEND_FROM_QUEUE';
